import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";
import { useEffect } from "react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full flex-col items-center justify-center bg-black text-white">
        <AuthShowcase />
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const createBlog = trpc.user.createBlog.useMutation();
  const getBlogs = trpc.user.getBlogs.useQuery();

  useEffect(() => {
    if (sessionData?.user?.id) {
      getBlogs.refetch();
    }
  }, [getBlogs, sessionData?.user?.id]);

  return (
    <div className="flex flex-col items-center justify-center gap-2">
      {!sessionData && (
        <p className="text-xl text-sky-100">Welcome to Metapod</p>
      )}
      {sessionData && (
        <p className="text-xl text-sky-100">
          Logged in as {sessionData?.user?.name}
        </p>
      )}
      <button
        className="rounded-md border px-3 py-2 text-xl text-white"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
      <button
        type="button"
        className="rounded-md border px-3 py-2 text-xl text-white"
        onClick={() => {
          createBlog.mutate({
            title: `Test Blog by ${sessionData?.user?.email}`,
            content: `Testing blog by admin ${sessionData?.user?.name}`,
          });
        }}
      >
        Create Blog
      </button>
      {getBlogs.data?.map((blog, i) => (
        <div key={blog.id}>
          {i} --- {blog.title} --- {blog.content} ---{" "}
          {blog.createdAt.toTimeString()}
        </div>
      ))}
    </div>
  );
};
